-- ============================================================
-- Mundo de Artanis -- Bestiario
-- Seed de monstros gerado a partir do MonsterDatabase.json
-- ============================================================

USE artanis_planner;

-- Limpa a tabela antes de inserir (seguro reexecutar este script)
DELETE FROM monsters;
ALTER TABLE monsters AUTO_INCREMENT = 1;

INSERT INTO monsters
  (game_id, name, level, is_boss, str_stat, agi_stat, int_stat, dex_stat, vit_stat, luk_stat,
   element, element_level, lore, atk_override, atk_bonus_override, drops, areas)
VALUES
  (2001, 'Cobra', 1, 0, 3, 2, 1, 3, 1, 3, 'terra', 1, 'Cobra dos arbustos baixos, cujo veneno causa paralisia temporária. Se imóvel, é praticamente invisível no capim. A maioria das mordidas acontece sem que a vítima a tenha visto.', NULL, NULL, '[{"itemName": "Dente de Cobra", "itemId": 1105, "chance": 0.5}, {"itemName": "Couro de Cobra", "itemId": 1106, "chance": 0.4}, {"itemName": "Bili de Cobra", "itemId": 1107, "chance": 0.3}]', '["floresta_selvagem", "arredores_da_cidade"]'),
  (2001, 'Cobra', 2, 0, 5, 2, 2, 4, 1, 4, 'terra', 1, 'Cobra dos arbustos baixos, cujo veneno causa paralisia temporária. Se imóvel, é praticamente invisível no capim. A maioria das mordidas acontece sem que a vítima a tenha visto.', NULL, NULL, '[{"itemName": "Dente de Cobra", "itemId": 1105, "chance": 0.5}, {"itemName": "Couro de Cobra", "itemId": 1106, "chance": 0.4}, {"itemName": "Bili de Cobra", "itemId": 1107, "chance": 0.4}]', '["tunel_escuro"]'),
  (2002, 'Corvo', 1, 0, 3, 3, 1, 3, 1, 2, 'neutro', 1, 'Corvos comuns dos arredores que desenvolveram comportamento agressivo em grupos. Atacam olhos e distraem enquanto companheiros roubam suprimentos. Mais inteligentes do que parecem — muito mais.', NULL, NULL, '[{"itemName": "Pena de Corvo", "itemId": 1086, "chance": 0.5}, {"itemName": "Bico de Corvo", "itemId": 1087, "chance": 0.2}, {"itemName": "Sangue de Corvo", "itemId": 1089, "chance": 0.3}]', '["floresta_selvagem", "arredores_da_cidade"]'),
  (2003, 'Goblin', 1, 0, 5, 2, 1, 1, 2, 2, 'neutro', 1, 'A ameaça mais frequente dos arredores. Individualmente covarde, em grupos torna-se ousado demais. Rouba, mente e foge — na ordem que for mais conveniente no momento.', NULL, NULL, '[{"itemName": "Adaga Velha", "itemId": 1090, "chance": 0.4}, {"itemName": "Cabeça de Goblin", "itemId": 1091, "chance": 0.15}]', '["floresta_selvagem", "arredores_da_cidade"]'),
  (2004, 'Javali Selvagem', 1, 0, 5, 1, 1, 1, 4, 1, 'neutro', 1, 'Onívoro territorial que defende seu espaço com carga direta. Suas presas causam ferimentos feios em quem não se posicionar corretamente. Caçadores o respeitam mais do que qualquer outro animal dos arredores.', NULL, NULL, '[{"itemName": "Presa de Javali", "itemId": 1081, "chance": 0.5}, {"itemName": "Pele de Javali", "itemId": 1083, "chance": 0.35}, {"itemName": "Dente de Javali", "itemId": 1082, "chance": 0.2}, {"itemName": "Pele de Javali Danificada", "itemId": 1084, "chance": 0.2}]', '["floresta_selvagem"]'),
  (2005, 'Lobo Selvagem', 1, 0, 5, 2, 1, 1, 3, 1, 'neutro', 1, 'O predador mais comum dos arredores. Caça em matilhas e coordena ataques com sinais sonoros que aventureiros mais experientes aprendem a reconhecer. Individualmente fraco — em grupo, uma ameaça real.', NULL, NULL, '[{"itemName": "Dente de Lobo", "itemId": 1071, "chance": 0.5}, {"itemName": "Garra de Lobo", "itemId": 1072, "chance": 0.4}, {"itemName": "Pele de Lobo", "itemId": 1073, "chance": 0.3}, {"itemName": "Pele de Lobo Danificada", "itemId": 1074, "chance": 0.15}]', '["floresta_selvagem", "arredores_da_cidade"]'),
  (2006, 'Raposa Selvagem', 1, 0, 3, 4, 1, 3, 1, 1, 'neutro', 1, 'Predador pequeno e ágil dos arredores da cidade. Inteligente o suficiente para evitar armadilhas simples e roubar suprimentos de acampamentos. Aventureiros iniciantes subestimam sua velocidade com frequência fatal.', NULL, NULL, '[{"itemName": "Dente de Raposa", "itemId": 1076, "chance": 0.5}, {"itemName": "Garra de Raposa", "itemId": 1077, "chance": 0.4}, {"itemName": "Pele de Raposa", "itemId": 1078, "chance": 0.3}, {"itemName": "Orelha de Raposa", "itemId": 1080, "chance": 0.15}]', '["floresta_selvagem"]'),
  (2007, 'Aranha', 2, 0, 5, 4, 2, 3, 1, 3, 'terra', 1, 'Aranha de médio porte que constrói teias entre árvores nos caminhos. Seu veneno é fraco, mas a teia pode deter aventureiros desatentos por tempo suficiente para que ela chame companheiras.', NULL, NULL, '[{"itemName": "Olho de Aranha", "itemId": 1097, "chance": 0.5}, {"itemName": "Teia de Aranha", "itemId": 1098, "chance": 0.6}, {"itemName": "Pernas de Aranha", "itemId": 1099, "chance": 0.2}]', '["tunel_escuro"]'),
  (2008, 'Centopeia', 2, 0, 7, 1, 1, 2, 6, 1, 'terra', 1, 'Miriápode que habita a vegetação úmida da floresta. Seus múltiplos segmentos regeneram ferimentos leves rapidamente. Ferreiros usam sua carapaça como material para armaduras leves.', NULL, NULL, '[{"itemName": "Presas de Centopeia", "itemId": 1100, "chance": 0.5}, {"itemName": "Ferrão de Centopeia", "itemId": 1101, "chance": 0.4}, {"itemName": "Carapaça de Centopeia", "itemId": 1102, "chance": 0.4}, {"itemName": "Pernas de Centopeia", "itemId": 1103, "chance": 0.15}, {"itemName": "Antenas de Centopeia", "itemId": 1104, "chance": 0.15}]', '["tunel_escuro"]'),
  (2009, 'Goblin Arqueiro', 2, 0, 5, 2, 1, 6, 1, 3, 'terra', 1, 'Subespecialidade goblin com mira surpreendentemente boa. Mantém distância e atrapalha enquanto companheiros avançam. Prioridade alta em qualquer confronto com goblins mistos.', NULL, NULL, '[{"itemName": "Cabeça de Goblin", "itemId": 1091, "chance": 0.2}]', '["bosque_encantado"]'),
  (2010, 'Goblin Astuto', 2, 1, 16, 1, 1, 2, 1, 1, 'neutro', 2, 'Goblin mais velho e esperto que sobreviveu à seleção natural dos arredores. Usa armadilhas improvisadas e raramente luta em desvantagem. Tem um valor de recompensa na guilda há mais de dois anos.', NULL, NULL, '[{"itemName": "Adaga Serrilhada", "itemId": 1213, "chance": 0.15}, {"itemName": "Cabeça de Goblin Astuto", "itemId": 1096, "chance": 0.25}]', '["floresta_selvagem"]'),
  (2011, 'Goblin Escavador', 2, 0, 7, 1, 1, 3, 5, 1, 'neutro', 1, 'Especialidade da subespécie — cava túneis sob os caminhos para emboscadas vindo de baixo. O chão cedendo sob os pés é sinal de que um grupo já está ao redor.', NULL, NULL, '[{"itemName": "Adaga Velha", "itemId": 1090, "chance": 0.35}, {"itemName": "Cabeça de Goblin", "itemId": 1091, "chance": 0.15}]', '["tunel_escuro"]'),
  (2012, 'Lobo Furioso', 2, 0, 9, 3, 1, 1, 2, 2, 'terra', 2, 'Lobo que perdeu sua matilha e caça sozinho com agressividade desesperada. Mais perigoso que os lobos em grupo justamente por não recuar quando deveria.', NULL, NULL, '[{"itemName": "Dente de Lobo", "itemId": 1071, "chance": 0.45}, {"itemName": "Garra de Lobo", "itemId": 1072, "chance": 0.45}, {"itemName": "Pele de Lobo", "itemId": 1073, "chance": 0.25}]', '["bosque_encantado"]'),
  (2013, 'Aranha Aquatica', 3, 0, 7, 4, 2, 5, 2, 3, 'agua', 1, 'Aranha adaptada para caçar próxima a fontes de água. Seu veneno é mais potente que o das aranhas terrestres — e seu território é exatamente onde aventureiros param para descansar.', NULL, NULL, '[{"itemName": "Olho de Aranha", "itemId": 1097, "chance": 0.4}, {"itemName": "Teia de Aranha", "itemId": 1098, "chance": 0.5}]', '["lago_tranquilidade"]'),
  (2014, 'Bandido', 3, 1, 11, 2, 1, 6, 4, 4, 'neutro', 1, 'Humano que escolheu a vida fora da lei nos caminhos entre as cidades. Mais perigoso que a maioria dos animais por ser imprevisível — e por saber exatamente como aventureiros pensam.', NULL, NULL, '[{"itemName": "Adaga Velha", "itemId": 1090, "chance": 0.3}]', '["bosque_encantado"]'),
  (2015, 'Escorpiao', 3, 0, 9, 1, 1, 4, 6, 2, 'sombrio', 2, 'Escorpião de médio porte dos caminhos pedregosos. Seu ferrão paralisa temporariamente — estratégia que usa para imobilizar presas maiores antes de atacar com as quelas.', NULL, NULL, '[{"itemName": "Ferrão de Centopeia", "itemId": 1101, "chance": 0.4}, {"itemName": "Presas de Centopeia", "itemId": 1100, "chance": 0.35}, {"itemName": "Bili de Cobra", "itemId": 1107, "chance": 0.25}]', '["bosque_encantado"]'),
  (2016, 'Lobo Alfa', 3, 1, 8, 6, 1, 5, 4, 4, 'terra', 1, 'Líder da matilha — maior, mais esperto e mais resistente que os outros. Sua presença transforma lobos comuns em caçadores coordenados. Derrotá-lo dispersa o grupo inteiro.', NULL, NULL, '[{"itemName": "Dente de Lobo Alfa", "itemId": 1092, "chance": 0.6}, {"itemName": "Garra de Lobo Alfa", "itemId": 1093, "chance": 0.5}, {"itemName": "Pele de Lobo Alfa", "itemId": 1094, "chance": 0.4}, {"itemName": "Pele de Lobo Alfa Danificada", "itemId": 1095, "chance": 0.2}]', '["floresta_selvagem"]'),
  (2017, 'Mosquito Gigante', 3, 0, 7, 6, 1, 4, 1, 4, 'vento', 1, 'Uma variação monstruosa do inseto comum, amplificada pela magia corrompida do pântano. Ágil e irritante, drena o sangue de qualquer criatura que se aventure perto das águas estagnadas.', NULL, NULL, '[{"itemName": "Sangue de Corvo", "itemId": 1089, "chance": 0.45}, {"itemName": "Teia de Aranha", "itemId": 1098, "chance": 0.3}]', '["pantano_escuro"]'),
  (2018, 'Viuva Negra', 3, 1, 14, 3, 1, 5, 1, 4, 'sombrio', 2, 'A mais venenosa das aranhas dos arredores. Seu veneno atua em minutos e aventureiros sem antídoto têm pouco tempo para agir. Reconhecida pela coloração característica — aqueles que sobrevivem ao encontro.', NULL, NULL, '[{"itemName": "Olho de Viuva Negra", "itemId": 1113, "chance": 0.5}, {"itemName": "Ferrão de Viuva Negra", "itemId": 1114, "chance": 0.5}, {"itemName": "Bolsa de Veneno de Viuva Negra", "itemId": 1115, "chance": 0.3}, {"itemName": "Pernas de Viuva Negra", "itemId": 1116, "chance": 0.2}]', '["tunel_escuro"]'),
  (2019, 'Centopeia Atroz', 4, 1, 6, 5, 1, 8, 8, 6, 'terra', 2, 'Versão maior e mais agressiva da centopeia comum. Seus segmentos blindados são resistentes demais para golpes sem técnica. Alquimistas pagam fortunas pelas presas inteiras.', NULL, NULL, '[{"itemName": "Presas de Centopeia Atroz", "itemId": 1108, "chance": 0.6}, {"itemName": "Ferrão de Centopeia Atroz", "itemId": 1109, "chance": 0.5}, {"itemName": "Carapaça de Centopeia Atroz", "itemId": 1110, "chance": 0.25}, {"itemName": "Pernas de Centopeia Atroz", "itemId": 1111, "chance": 0.2}, {"itemName": "Antenas de Centopeia Atroz", "itemId": 1112, "chance": 0.2}]', '["tunel_escuro"]'),
  (2020, 'Centopeia do Pantano', 4, 0, 8, 1, 1, 4, 12, 2, 'agua', 2, 'Centopeia de grande porte adaptada ao ambiente úmido do pântano. Seu veneno não mata diretamente — apenas enfraquece a vítima até que as outras criaturas do pântano possam atacar.', NULL, NULL, '[{"itemName": "Presas de Centopeia", "itemId": 1100, "chance": 0.4}, {"itemName": "Ferrão de Centopeia", "itemId": 1101, "chance": 0.4}, {"itemName": "Carapaça de Centopeia", "itemId": 1102, "chance": 0.3}]', '["pantano_escuro"]'),
  (2021, 'Serpente Aquatica', 4, 0, 10, 3, 1, 5, 4, 5, 'agua', 2, 'Serpente que caça sob a superfície de lagos e riachos. Ataca antes mesmo de ser vista. Viajantes aprenderam a não encher cantis com a mão na água.', NULL, NULL, '[{"itemName": "Dente de Cobra", "itemId": 1105, "chance": 0.5}, {"itemName": "Couro de Cobra", "itemId": 1106, "chance": 0.4}]', '["lago_tranquilidade"]'),
  (2022, 'Tartaruga Gigante', 4, 1, 10, 1, 2, 2, 14, 5, 'agua', 2, 'Quelônio de grande porte que habita as margens do lago. Inofensiva se ignorada — mas sua carapaça resiste praticamente a qualquer ataque frontal, frustrando aventureiros impaciantes.', NULL, NULL, '[{"itemName": "Carapaça de Centopeia", "itemId": 1102, "chance": 0.5}, {"itemName": "Couro de Cobra", "itemId": 1106, "chance": 0.4}]', '["lago_tranquilidade"]'),
  (2023, 'Bandido do Deserto', 5, 0, 9, 4, 1, 5, 9, 5, 'terra', 3, 'Versão mais dura do bandido comum, adaptada à sobrevivência extrema. Conhece rotas de fuga pela savana que aventureiros de fora nunca encontrariam.', NULL, NULL, '[{"itemName": "Adaga Velha", "itemId": 1090, "chance": 0.25}]', '["savana"]'),
  (2024, 'Crocodilo Pantanoso', 5, 1, 6, 7, 1, 7, 7, 12, 'agua', 2, 'Predador ancestral que habita as águas turvas do pântano. Sua pele endurecida resiste a golpes físicos comuns, e a mandíbula é capaz de esmagar ossos com um único bite.', NULL, NULL, '[{"itemName": "Couro de Cobra", "itemId": 1106, "chance": 0.4}]', '["pantano_escuro"]'),
  (2025, 'Hiena Faminta', 5, 0, 9, 5, 1, 4, 9, 5, 'neutro', 2, 'Hiena que perdeu acesso às presas habituais e avança para território humano. A fome a torna imprevisível e mais agressiva do que o normal para a espécie.', NULL, NULL, '[{"itemName": "Presas de Hiena", "itemId": 1119, "chance": 0.5}, {"itemName": "Trapos de Bandido", "itemId": 1122, "chance": 0.2}]', '["savana"]'),
  (2026, 'Olho Demoniano', 5, 0, 7, 1, 1, 6, 13, 5, 'vento', 2, 'Criatura flutuante de origem obscura que aparece nos pântanos ao entardecer. Seu único órgão visível — o olho central — emite um brilho que desorientava viajantes antes de qualquer entendimento sobre a criatura.', NULL, NULL, '[{"itemName": "Olho Demoniano", "itemId": 1126, "chance": 0.5}, {"itemName": "Essencia Sombria", "itemId": 1127, "chance": 0.4}]', '["arredores_cidade_intermediaria"]'),
  (2027, 'Chacal das Dunas', 6, 0, 9, 8, 1, 6, 9, 5, 'terra', 2, 'Predador das regiões áridas que se move em pequenos grupos. Mais veloz que parece, o chacal das dunas usa o calor da savana para confundir presas que subestimam sua resistência ao sol.', NULL, NULL, '[{"itemName": "Pele de Raposa", "itemId": 1078, "chance": 0.4}, {"itemName": "Presa de Hiena", "itemId": 1164, "chance": 0.3}]', '["savana"]'),
  (2028, 'Escorpiao Gigante', 6, 1, 7, 7, 1, 10, 8, 13, 'terra', 3, 'Escorpião do tamanho de um cachorro médio, com ferrão que atravessa armaduras de couro com facilidade. Seu veneno age mais devagar que o do escorpião comum — mas os efeitos são proporcionalmente mais severos.', NULL, NULL, '[{"itemName": "Ferrão de Escorpiao Gigante", "itemId": 1120, "chance": 0.55}, {"itemName": "Veneno de Escorpiao", "itemId": 1121, "chance": 0.4}]', '["savana"]'),
  (2029, 'Harpia', 6, 1, 18, 9, 1, 5, 1, 12, 'vento', 2, 'Criatura alada que usa a altura para vantagem absoluta. Seu grito ensurdecedor desorientam temporariamente — arma usada antes de cada mergulho de ataque.', NULL, NULL, '[{"itemName": "Pena de Harpia", "itemId": 1124, "chance": 0.55}, {"itemName": "Garra de Harpia", "itemId": 1125, "chance": 0.45}]', '["arredores_cidade_intermediaria"]'),
  (2030, 'Leao da Savana', 6, 1, 6, 8, 1, 6, 16, 9, 'neutro', 2, 'O maior predador terrestre da savana. Caça com paciência calculada, esperando horas pela posição ideal. Aventureiros que o veem espiar pela vegetação já foram avaliados e escolhidos como presas.', NULL, NULL, '[{"itemName": "Juba de Leao", "itemId": 1117, "chance": 0.35}, {"itemName": "Garra de Leao", "itemId": 1118, "chance": 0.45}, {"itemName": "Pelo de Urso Polar", "itemId": 1130, "chance": 0.1}]', '["savana"]'),
  (2031, 'Lobo Sombrio', 6, 0, 8, 6, 1, 4, 15, 4, 'agua', 2, 'Lobo de pelagem negra que caça exclusivamente à noite. Suas pupilas são adaptadas ao escuro absoluto — vantagem que cancela a maioria das estratégias defensivas padrão.', NULL, NULL, '[{"itemName": "Pelo de Lobo Sombrio", "itemId": 1128, "chance": 0.45}, {"itemName": "Essencia Sombria", "itemId": 1127, "chance": 0.3}]', '["arredores_cidade_intermediaria"]'),
  (2032, 'Serpente de Areia', 6, 0, 7, 9, 1, 8, 7, 6, 'terra', 2, 'Cobra venenosa que se enterra na areia entre os ataques. Aventureiros inexperientes pisam onde ela está antes de perceber. Seu veneno não mata rápido — mas paralisa o suficiente para ser fatal.', NULL, NULL, '[{"itemName": "Dente de Cobra", "itemId": 1105, "chance": 0.45}, {"itemName": "Couro de Cobra", "itemId": 1106, "chance": 0.35}]', '["savana"]'),
  (2033, 'Arqueiro Renegado', 7, 0, 6, 8, 1, 12, 8, 8, 'neutro', 1, 'Ex-soldado que abandonou o serviço militar e agora usa suas habilidades para sobreviver nos arredores. Preciso e calculista, evita confronto direto e prefere atacar de longe.', NULL, NULL, '[{"itemName": "Trapos de Bandido", "itemId": 1122, "chance": 0.25}]', '["arredores_cidade_intermediaria"]'),
  (2034, 'Cavaleiro Errante', 7, 1, 6, 8, 1, 10, 10, 17, 'terra', 1, 'Guerreiro humano cujo passado é desconhecido. Vagueia pelos caminhos atacando sem distinção — trauma, maldição ou simples loucura. Seu equipamento sugere que um dia foi alguém respeitado.', NULL, NULL, '[{"itemName": "Fragmento de Armadura", "itemId": 1123, "chance": 0.6}, {"itemName": "Trapos de Bandido", "itemId": 1122, "chance": 0.3}]', '["arredores_cidade_intermediaria"]'),
  (2035, 'Cobra de Duas Cabecas', 7, 0, 6, 7, 1, 8, 11, 10, 'terra', 2, 'Mutação rara encontrada nas encostas geladas. Cada cabeça age de forma independente, tornando seus movimentos imprevisíveis. O veneno de uma cabeça congela; o da outra paralisa.', NULL, NULL, '[{"itemName": "Dente de Cobra", "itemId": 1105, "chance": 0.5}, {"itemName": "Couro de Cobra", "itemId": 1106, "chance": 0.4}, {"itemName": "Bili de Cobra", "itemId": 1107, "chance": 0.4}]', '["montanha_gelada"]'),
  (2036, 'Golem de Pedra Menor', 7, 0, 8, 1, 1, 6, 19, 8, 'terra', 3, 'Golem construído com pedras comuns dos arredores, animado por magia residual. Menor e mais primitivo que os golems das ruínas antigas, ainda assim representa uma ameaça sólida para quem não está preparado.', NULL, NULL, '[{"itemName": "Fragmento de Armadura", "itemId": 1123, "chance": 0.4}]', '["arredores_cidade_intermediaria"]'),
  (2037, 'Aguia de Gelo', 8, 0, 10, 12, 1, 13, 6, 10, 'agua', 2, 'Águia que domina as correntes de ar gélido das montanhas altas. Seus olhos enxergam com precisão cirúrgica a centenas de metros. Ataca em mergulho quando menos se espera.', NULL, NULL, '[{"itemName": "Pena de Harpia", "itemId": 1124, "chance": 0.45}, {"itemName": "Garra de Lobo Alfa", "itemId": 1093, "chance": 0.3}]', '["montanha_gelada"]'),
  (2038, 'Caranguejo do Pantano', 8, 0, 7, 3, 1, 8, 22, 7, 'agua', 2, 'Caranguejo de carapaça endurecida que vive nas águas rasas do pântano. Lento mas praticamente impenetrável de frente. Mineiros e pescadores o respeitam — sua pinça pode quebrar ossos.', NULL, NULL, '[{"itemName": "Lodo Purpura", "itemId": 1185, "chance": 0.45}, {"itemName": "Couro de Cobra", "itemId": 1106, "chance": 0.35}]', '["pantano_andar2"]'),
  (2039, 'Elemental de Gelo', 8, 1, 11, 10, 1, 8, 2, 26, 'agua', 4, 'Manifestação pura da energia glacial da montanha. Não possui corpo orgânico — é formado inteiramente por cristais de gelo animados pela magia do inverno eterno. Invulnerável ao frio, vulnerável ao calor.', NULL, NULL, '[{"itemName": "Cristal de Gelo", "itemId": 1131, "chance": 0.6}, {"itemName": "Nucleo de Elemental", "itemId": 1132, "chance": 0.35}]', '["montanha_gelada"]'),
  (2040, 'Lobo do Permafrost', 8, 0, 9, 11, 1, 8, 12, 7, 'agua', 2, 'Lobo adaptado ao gelo permanente das montanhas. Seu pelo duplo o protege de temperaturas que matariam outros predadores. Caça em silêncio — a neve abafa seus passos.', NULL, NULL, '[{"itemName": "Pelo de Lobo Sombrio", "itemId": 1128, "chance": 0.45}, {"itemName": "Dente de Lobo Alfa", "itemId": 1092, "chance": 0.3}]', '["montanha_gelada"]'),
  (2040, 'Lobo do Permafrost', 10, 0, 12, 14, 2, 12, 12, 10, 'agua', 2, 'Lobo adaptado ao gelo permanente das montanhas. Seu pelo duplo o protege de temperaturas que matariam outros predadores. Caça em silêncio — a neve abafa seus passos.', NULL, NULL, '[{"itemName": "Cristal de Gelo Puro", "itemId": 1191, "chance": 0.45}, {"itemName": "Pelo de Urso Polar", "itemId": 1130, "chance": 0.4}]', '["montanha_andar2"]'),
  (2041, 'Sapo Gigante', 8, 0, 8, 4, 3, 6, 20, 6, 'agua', 2, 'Anfíbio colossal que evoluiu isolado nas profundezas pantanosas. Sua língua viscosa alcança distâncias surpreendentes, e seu corpo absorve venenos do ambiente — tornando-o tóxico ao contato. Lento, mas extraordinariamente resistente.', NULL, NULL, '[{"itemName": "Lodo Purpura", "itemId": 1185, "chance": 0.55}, {"itemName": "Bili de Cobra", "itemId": 1107, "chance": 0.45}]', '["pantano_andar2"]'),
  (2042, 'Urso Polar', 8, 1, 7, 6, 1, 8, 15, 21, 'sombrio', 2, 'Predador máximo das alturas congeladas. Sua musculatura é capaz de derrubar árvores com um único golpe de pata. O pelo denso o protege de temperaturas que matariam qualquer aventureiro despreparado.', NULL, NULL, '[{"itemName": "Garra de Urso Polar", "itemId": 1129, "chance": 0.55}, {"itemName": "Pelo de Urso Polar", "itemId": 1130, "chance": 0.6}]', '["montanha_gelada"]'),
  (2044, 'Espectro do Pantano', 9, 0, 12, 12, 14, 10, 6, 14, 'sombra', 2, 'Entidade espiritual formada pela corrupção mágica das águas profundas. Não possui forma física estável — flutua entre o plano material e o plano sombrio, tornando-se difícil de acertar com ataques físicos. Emite um olhar que drena a vitalidade de quem o enfrenta.', NULL, NULL, '[{"itemName": "Olho de Pantano", "itemId": 1188, "chance": 0.5}, {"itemName": "Lodo Purpura", "itemId": 1185, "chance": 0.35}]', '["pantano_andar2"]'),
  (2045, 'Hidra do Pantano', 9, 0, 10, 10, 4, 10, 14, 8, 'agua', 3, 'Criatura de múltiplas cabeças que habita as regiões mais fundas do pântano. Dizem que cada cabeça cortada regenera duas — apenas aventureiros de alto nível conseguem deter sua capacidade de regeneração. Suas escamas têm propriedades alquímicas valiosas.', NULL, NULL, '[{"itemName": "Couro de Cobra", "itemId": 1106, "chance": 0.5}, {"itemName": "Lodo Purpura", "itemId": 1185, "chance": 0.6}, {"itemName": "Escama de Hidra", "itemId": 1186, "chance": 0.35}]', '["pantano_andar2"]'),
  (2059, 'Criatura do Abismo', 11, 0, 16, 8, 2, 10, 26, 8, 'sombra', 3, 'Uma aberração sem nome, surgida das profundezas mais escuras do pântano. Sua origem é desconhecida — possivelmente um ser corrompido por séculos de exposição à magia sombria das águas do abismo. Não ataca por fome. Ataca porque existe.', NULL, NULL, '[{"itemName": "Osso do Abismo", "itemId": 1189, "chance": 0.55}, {"itemName": "Lodo Purpura", "itemId": 1185, "chance": 0.4}]', '["pantano_andar3"]'),
  (2060, 'Elemental do Blizzard', 11, 0, 4, 10, 20, 12, 10, 18, 'agua', 4, 'Versão amplificada do Elemental de Gelo, formada no núcleo das tempestades do glaciar eterno. Controla ventos e neve com precisão cirúrgica. Seu simples contato congela qualquer superfície e pode paralisar aventureiros não-resistentes ao elemento gelo.', NULL, NULL, '[{"itemName": "Essencia Glacial", "itemId": 1194, "chance": 0.5}, {"itemName": "Cristal de Gelo Puro", "itemId": 1191, "chance": 0.55}]', '["montanha_andar2"]'),
  (2070, 'Yeti', 11, 0, 18, 3, 2, 6, 28, 4, 'agua', 3, 'Criatura das alturas que os montanheses temem há gerações. Seu tamanho impressionante — quase o dobro de um humano adulto — é compensado pela lentidão dos movimentos. O pelo grosso age como armadura natural contra golpes físicos. Altamente territorial e extremamente agressivo com intrusos.', NULL, NULL, '[{"itemName": "Pelo de Yeti", "itemId": 1192, "chance": 0.6}, {"itemName": "Cristal de Gelo Puro", "itemId": 1191, "chance": 0.4}]', '["montanha_andar2"]'),
  (2073, 'Basilisco do Pantano', 12, 0, 18, 10, 8, 14, 22, 12, 'agua', 4, 'Réptil lendário de proporções colossais, o Basilisco do Pântano é uma variante aquática do temido basilisco das terras áridas. Seu veneno é incomparável — dissolve armaduras e paralisa o sistema nervoso. Não é o verdadeiro chefe do abismo, mas poucos aventureiros chegam vivos até ele.', NULL, NULL, '[{"itemName": "Veneno de Basilisco", "itemId": 1187, "chance": 0.65}, {"itemName": "Escama de Hidra", "itemId": 1186, "chance": 0.5}]', '["pantano_andar3"]'),
  (2094, 'Guardiao do Cume', 14, 0, 20, 8, 6, 12, 36, 12, 'agua', 4, 'Colosso de pedra e gelo que protege a entrada do Trono do Inverno. Não é um ser vivo no sentido estrito — foi criado há séculos por uma civilização desaparecida para guardar o que está acima. Sua resistência é lendária: sobreviveu a inúmeras expedições de aventureiros. Derrotá-lo é pré-requisito para enfrentar o verdadeiro horror do cume.', NULL, NULL, '[{"itemName": "Garra do Permafrost", "itemId": 1193, "chance": 0.65}, {"itemName": "Essencia Glacial", "itemId": 1194, "chance": 0.45}]', '["montanha_andar3"]'),
  (2096, 'Senhor do Pantano', 14, 1, 22, 14, 12, 16, 30, 18, 'sombra', 4, 'A entidade mais antiga que habita o pântano — tão velha quanto o próprio lamaçal. Nenhum registro histórico descreve sua forma com precisão, pois os poucos que a viram não voltaram para contar. Controla as criaturas do pântano como extensões de sua vontade. Derrotá-lo é considerado façanha impossível por aventureiros comuns.', NULL, NULL, '[{"itemName": "Nucleo do Abismo", "itemId": 1190, "chance": 0.7}, {"itemName": "Veneno de Basilisco", "itemId": 1187, "chance": 0.6}, {"itemName": "Osso do Abismo", "itemId": 1189, "chance": 0.8}]', '["pantano_andar3"]'),
  (2098, 'Dragao de Gelo Jovem', 15, 0, 18, 12, 16, 14, 28, 16, 'agua', 5, 'Um dragão ainda em crescimento, mas já de porte avassalador. Escolheu os picos da Montanha Gelada como lar — o frio extremo alimenta seu poder elemental. Seu sopro congela instantaneamente qualquer alvo. Por ser jovem, é mais agressivo e imprevisível do que dragões maduros. O Coração do Inverno que carrega é o material mais valioso do Ato 1.', NULL, NULL, '[{"itemName": "Coracao do Inverno", "itemId": 1195, "chance": 0.55}, {"itemName": "Cristal de Gelo Puro", "itemId": 1191, "chance": 0.65}]', '["montanha_andar3"]'),
  (2118, 'Tita do Gelo', 18, 1, 30, 10, 20, 16, 50, 20, 'agua', 5, 'A criatura mais poderosa conhecida no Ato 1 — um titã primordial de gelo eterno que reina no Trono do Inverno há milênios. Nenhuma expedição registrada sobreviveu ao encontro com ele. Sua presença altera o clima da região inteira: quando desperta, tempestades de neve cobrem toda a Montanha Gelada. O Núcleo do Gelo Eterno que carrega é a essência de seu poder — e a recompensa máxima para quem ouse desafiá-lo.', NULL, NULL, '[{"itemName": "Nucleo do Gelo Eterno", "itemId": 1196, "chance": 0.75}, {"itemName": "Coracao do Inverno", "itemId": 1195, "chance": 0.7}, {"itemName": "Essencia Glacial", "itemId": 1194, "chance": 0.8}]', '["montanha_andar3"]'),
  (9001, 'Boneco de Treino', 1, 0, 1, 1, 1, 1, 50, 1, 'neutro', 1, 'Um boneco de palha reforçado usado para treinamento básico no Centro de Treino. Causa dano mínimo e serve como alvo para aprender técnicas de combate.', 1, 0, '[]', '["treino_ci"]'),
  (9002, 'Boneco de Treino Avancado', 1, 0, 1, 1, 1, 1, 500, 1, 'neutro', 1, 'Um boneco de treino reforçado com armadura pesada. Possui HP extremamente elevado para testes de DPS prolongados. Causa apenas 1 de dano por ataque.', 1, 0, '[]', '["treino_ci"]');
